##Array

Convention for importing numpy


In [25]:
import numpy as np
arr = (1,2,3,4,5)
type(arr)

tuple

In [26]:
a = np.array(arr)
type(a)

numpy.ndarray

In [29]:
print(a.ndim)
print(a.shape)
print(a.dtype)

1
(5,)
int64


In [32]:
barr = [["a","b","c"],[1,2,3]]
type(barr)

list

In [34]:
b = np.array(barr)
print(b)

[['a' 'b' 'c']
 ['1' '2' '3']]


In [35]:
print(b.ndim)
print(b.shape)
print(b.dtype)

2
(2, 3)
<U21


Inbuild functions that can be used to initialize numpy

In [40]:
np.random.random((2,4)) #takes random value for array

array([[0.94884811, 0.06465564, 0.1756062 , 0.03636608],
       [0.39887329, 0.54738957, 0.64081698, 0.74777001]])

In [43]:
np.zeros((2,5), dtype = None) #array of 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.ones((2,2)) #array of 1

array([[1., 1.],
       [1., 1.]])

In [52]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Intra-oprability of arrays and scalars


In [58]:
m = np.array([[1,2,3],[2,6,11]])
n = np.array([[2,3,7],[4,9,1]])


In [61]:
print(m + n)
print(m**2)
print(1-n)
print(10/n+m)

[[ 3  5 10]
 [ 6 15 12]]
[[  1   4   9]
 [  4  36 121]]
[[-1 -2 -6]
 [-3 -8  0]]
[[ 6.          5.33333333  4.42857143]
 [ 4.5         7.11111111 21.        ]]


Slicing

In [66]:
print(m[:2])
print(n[:0,:2])

[[ 1  2  3]
 [ 2  6 11]]
[]
